model:
  model_name: "meta-llama/Llama-3.2-3B-Instruct"
  adapter_model: "aumoai/llama3.2-3B-lora-oumi-aumogpt-adapter" #"results/oumi/llama3b.lora"
  trust_remote_code: true
  torch_dtype_str: "bfloat16"
  model_kwargs:
    load_in_4bit: True

generation:
  max_new_tokens: 2048
  batch_size: 1