# QLora config for Llama 3.3 70B.
# Borrows param values from:
# https://github.com/pytorch/torchtune/blob/main/recipes/configs/llama3_3/70B_lora.yaml
# https://github.com/pytorch/torchtune/blob/main/recipes/configs/llama3_1/405B_qlora.yaml
#
# Requirements:
#   - Log into WandB (`wandb login`) or disable `enable_wandb`
#   - Log into HF: `huggingface-cli login`
#   - Request access to Llama 3.3: https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct
#
# Usage:
#   oumi train -c configs/recipes/llama3_3/sft/70b_qlora/train.yaml
#
# See Also:
#   - Documentation: https://oumi.ai/docs/en/latest/user_guides/train/train.html
#   - Config class: oumi.core.configs.TrainingConfig
#   - Config source: https://github.com/oumi-ai/oumi/blob/main/src/oumi/core/configs/training_config.py
#   - Other training configs: configs/**/pretraining/, configs/**/sft/, configs/**/dpo/

model:
  model_name: "meta-llama/Llama-3.2-3B-Instruct"
  model_max_length: 2048
  torch_dtype_str: "bfloat16"
  attn_implementation: "sdpa"
  load_pretrained_weights: True
  trust_remote_code: True

data:
  train:
    datasets:
      - dataset_name: "text_sft"
        dataset_path: "datasets/aumogpt_train.json"
  validation:
    datasets:
      - dataset_name: "text_sft"
        dataset_path: "datasets/aumogpt_validation.json"
        split: "validation"

training:
  trainer_type: "TRL_SFT"
  use_peft: False
  save_steps: 200
  num_train_epochs: 1
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 1
  max_grad_norm: null

  enable_gradient_checkpointing: True
  gradient_checkpointing_kwargs:
    use_reentrant: False
  ddp_find_unused_parameters: False
  optimizer: "adamw_torch"
  learning_rate: 2.0e-5
  warmup_steps: 10
  weight_decay: 0.01
  compile: False

  dataloader_num_workers: "auto"
  dataloader_prefetch_factor: 32

  logging_steps: 10
  log_model_summary: False
  empty_device_cache_steps: 50
  output_dir: "results/oumi/llama3b.sft"
  include_performance_metrics: True
  enable_wandb: False

  eval_strategy: "steps"                  # When to evaluate ("no", "steps", "epoch")
  eval_steps: 20

# fsdp:
#   enable_fsdp: True
#   forward_prefetch: True
#   sharding_strategy: "FULL_SHARD"
#   auto_wrap_policy: "TRANSFORMER_BASED_WRAP"
#   transformer_layer_cls: "LlamaDecoderLayer"

# output_adapter_name: "aumoai/llama3.2-3B-qlora-oumi-aumogpt-adapter-goes"